### ISSUE TITLE
Unable to download package

### ISSUE THREAD

**Issue by sauravg94** [martinctc/parallaxr#1]
devtools::install_github("martinctc/parallaxr")

_Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

  Did you spell the repo owner (`martinctc`) and repo name (`parallaxr`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo._

**Comment by martinctc** [comment]
Thanks for the issue! I've just ran the same line of code (`devtools::install_github("martinctc/parallaxr")`) but it worked for me - could you try: 
`devtools::install_git(url = "https://github.com/martinctc/parallaxr.git")` ?

**Comment by martinctc** [comment]
The point `No commit found for the ref master` is also interesting - I actually used the "main" branch rather than the "master" branch for this repo. Could you try updating your **devtools**?

**Comment by martinctc** [comment]
@sauravg94 Could you confirm if the above has resolved your issue?

**Comment by sauravg94** [comment]
devtools::install_git(url = "https://github.com/martinctc/parallaxr.git")
This worked. Thanks!
