### ISSUE TITLE
CSS modifications?

### ISSUE THREAD

**Issue by spcanelon** [martinctc/parallaxr#2]
👋 Hello @martinctc! This is a very cool package, thank you for developing and sharing it 👏 

I don't have the "Segoe UI" font family and the example html output is rendering with Times New Roman (please see screenshot below) 😢 

It'd be really helpful if we could pick our own fonts and style other elements of the doc. Would it be possible to modify the package so that the [`style.css`](https://github.com/martinctc/parallaxr/blob/main/inst/style.css) sheet is easily accessible somewhere for users to make their own changes?

![image](https://user-images.githubusercontent.com/49913337/99196576-4ea6e600-275b-11eb-96ea-8e13550288ad.png)

**Comment by martinctc** [comment]
Thank you @spcanelon! That's a great point. I can do two things:
- Provide more font options in the default CSS so that you won't get _Times New Roman_ even if your browser hasn't got _Segoe UI_
- Add an argument so the user can supply a custom CSS

**Comment by spcanelon** [comment]
Amazing! Both of those would be so nice!

Thanks for your willingness to incorporate these changes 😀

**Comment by martinctc** [comment]
@spcanelon - I've now added a pull request which incorporates some of these changes! 
 
You can now use `default_css()` to access the default CSS file, edit it, and supply it to a new argument to `generate_scroll_doc()`. Also, I've added some new font alternatives to `Segoe UI`, so it shouldn't be a problem with the browsers now. I'll still need to update the examples, but would you be interested in reviewing the functions (just basically test them and give feedback)? If so I can add you as a reviewer to the PR :smile:

https://github.com/martinctc/parallaxr/pull/3

**Comment by spcanelon** [comment]
Hi @martinctc, wow that was quick! 
I'd be happy to review/test the functions 👍
